# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-02 14:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nbr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hood',
            name='user',
        ),
        migrations.AlterField(
            model_name='hood',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
